// Common cryptocurrency symbols mapping
export const SYMBOL_MAPPINGS: Record<string, string> = {
  // Major cryptocurrencies
  'BTC': 'bitcoin',
  'ETH': 'ethereum',
  'SOL': 'solana',
  'ADA': 'cardano',
  'DOT': 'polkadot',
  'AVAX': 'avalanche-2',
  'MATIC': 'matic-network',
  'DOGE': 'dogecoin',
  'XRP': 'ripple',
  'LINK': 'chainlink',
  'UNI': 'uniswap',
  'ATOM': 'cosmos',
  'LTC': 'litecoin',
  'ALGO': 'algorand',
  'XLM': 'stellar',
  'VET': 'vechain',
  'HBAR': 'hedera-hashgraph',
  'ICP': 'internet-computer',
  'FIL': 'filecoin',
  'THETA': 'theta-token',
  'BONK': 'bonk',
  'JUP': 'jupiter',
  'PYTH': 'pyth-network',
  'RAY': 'raydium',
  'RNDR': 'render-token',
  'WIF': 'wif-token',
  'JTO': 'jito',
  'MYRIA': 'myria',
  'SHDW': 'genesysgo-shadow',
  'GALA': 'gala',
  'VR': 'victoria-vr',
  'DATA': 'streamr',
  'SEI': 'sei-network',
  'DYM': 'dymension',
  'ZETA': 'zeta',
  'STRK': 'starknet',
  'IMX': 'immutable-x',
  'MANTA': 'manta-network',
  'TIA': 'celestia',
  'PIXEL': 'pixels',
  'BLUR': 'blur',
  'ARB': 'arbitrum',
  'BNB': 'binancecoin',
  'FTM': 'fantom'
};